// AUTO-GENERATED by seed/src/schema/generate-types.ts — do not edit by hand

export interface Employees {
  id: string;
  status: string | null;
  sort: number | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
  email: string | null;
  tel: string | null;
  picture: string | null;
  contact_picture: string | null;
}

export interface EmployeesTranslations {
  id: string;
  languages_code: string | null;
  name: string | null;
  position: string | null;
}

export interface Brochures {
  id: string;
  status: string | null;
  sort: number | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
  thumbnail: string | null;
  file: string | null;
}

export interface BrochuresTranslations {
  id: string;
  languages_code: string | null;
  title: string | null;
}

export interface Downloads {
  id: string;
  status: string | null;
  sort: number | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
  file: string | null;
  sort_order: number | null;
}

export interface DownloadsTranslations {
  id: string;
  languages_code: string | null;
  title: string | null;
  description: string | null;
}

export interface Fairs {
  id: string;
  status: string | null;
  sort: number | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
  start_date: string | null;
  end_date: string | null;
  external_link: string | null;
  logo: string | null;
}

export interface FairsTranslations {
  id: string;
  languages_code: string | null;
  name: string | null;
  city: string | null;
  description: string | null;
  content: unknown | null;
}

export interface JobAds {
  id: string;
  status: string | null;
  sort: number | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
  file: string | null;
  sort_order: number | null;
}

export interface JobAdsTranslations {
  id: string;
  languages_code: string | null;
  title: string | null;
  description: string | null;
  content: unknown | null;
}

export interface SocialMediaChannels {
  id: string;
  status: string | null;
  sort: number | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
  name: string | null;
  external_link: string | null;
}

export interface Testimonials {
  id: string;
  status: string | null;
  sort: number | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
  timestamp: string | null;
  thumbnail: string | null;
}

export interface TestimonialsTranslations {
  id: string;
  languages_code: string | null;
  name: string | null;
  testimonial: unknown | null;
}

export interface ContactRequests {
  id: string;
  status: string | null;
  name: string | null;
  company: string | null;
  email: string | null;
  phone: string | null;
  message: string | null;
  page_url: string | null;
  recipient: string | null;
  date_created: string | null;
}

export interface CncMills {
  id: string;
  status: string | null;
  sort: number | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
  available: boolean | null;
  location: string | null;
  internal_id: string | null;
  year_of_manufacture: number | null;
  condition_key: string | null;
  priority: string | null;
  weight: string | null;
  dimensions: string | null;
  number_of_axes: number | null;
  travel_x: string | null;
  travel_y: string | null;
  travel_z: string | null;
  travel_a: string | null;
  travel_c: string | null;
  spindle_hours: string | null;
  machine_hours: string | null;
  clamping_surface: string | null;
  feed_rate_x: string | null;
  feed_rate_y: string | null;
  feed_rate_z: string | null;
  contact_person: string | null;
}

export interface CncMillsTranslations {
  id: string;
  languages_code: string | null;
  slug: string | null;
  name: string | null;
  designation: string | null;
  manufacturer: string | null;
  model_type: string | null;
  control_system: string | null;
  milling_spindle: string | null;
  tool_holder: string | null;
  description: unknown | null;
}

export interface ConventionalMills {
  id: string;
  status: string | null;
  sort: number | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
  available: boolean | null;
  location: string | null;
  internal_id: string | null;
  year_of_manufacture: number | null;
  condition_key: string | null;
  priority: string | null;
  weight: string | null;
  dimensions: string | null;
  machine_serial_number: string | null;
  spindle_speed: string | null;
  table_holder: string | null;
  table_size: string | null;
  power: string | null;
  contact_person: string | null;
}

export interface ConventionalMillsTranslations {
  id: string;
  languages_code: string | null;
  slug: string | null;
  name: string | null;
  designation: string | null;
  manufacturer: string | null;
  model_type: string | null;
  control_system: string | null;
  milling_spindle: string | null;
  tool_holder: string | null;
  description: unknown | null;
}

export interface Lathes {
  id: string;
  status: string | null;
  sort: number | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
  available: boolean | null;
  location: string | null;
  internal_id: string | null;
  year_of_manufacture: number | null;
  condition_key: string | null;
  priority: string | null;
  weight: string | null;
  dimensions: string | null;
  machine_serial_number: string | null;
  center_distance: string | null;
  center_height: string | null;
  power: string | null;
  contact_person: string | null;
}

export interface LathesTranslations {
  id: string;
  languages_code: string | null;
  slug: string | null;
  name: string | null;
  designation: string | null;
  manufacturer: string | null;
  model_type: string | null;
  control_system: string | null;
  milling_spindle: string | null;
  tool_holder: string | null;
  description: unknown | null;
}

export interface MillingMachines {
  id: string;
  status: string | null;
  sort: number | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
  available: boolean | null;
  location: string | null;
  internal_id: string | null;
  year_of_manufacture: number | null;
  condition_key: string | null;
  priority: string | null;
  weight: string | null;
  dimensions: string | null;
  machine_serial_number: string | null;
  table_height: string | null;
  table_size: string | null;
  contact_person: string | null;
}

export interface MillingMachinesTranslations {
  id: string;
  languages_code: string | null;
  slug: string | null;
  name: string | null;
  designation: string | null;
  manufacturer: string | null;
  model_type: string | null;
  control_system: string | null;
  milling_spindle: string | null;
  tool_holder: string | null;
  description: unknown | null;
}

export interface GrindingMachines {
  id: string;
  status: string | null;
  sort: number | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
  available: boolean | null;
  location: string | null;
  internal_id: string | null;
  year_of_manufacture: number | null;
  condition_key: string | null;
  priority: string | null;
  weight: string | null;
  dimensions: string | null;
  machine_serial_number: string | null;
  table_size: string | null;
  grinding_area: string | null;
  power: string | null;
  contact_person: string | null;
}

export interface GrindingMachinesTranslations {
  id: string;
  languages_code: string | null;
  slug: string | null;
  name: string | null;
  designation: string | null;
  manufacturer: string | null;
  model_type: string | null;
  control_system: string | null;
  milling_spindle: string | null;
  tool_holder: string | null;
  description: unknown | null;
  type: string | null;
}

export interface DrillingMachines {
  id: string;
  status: string | null;
  sort: number | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
  available: boolean | null;
  location: string | null;
  internal_id: string | null;
  year_of_manufacture: number | null;
  condition_key: string | null;
  priority: string | null;
  weight: string | null;
  dimensions: string | null;
  machine_serial_number: string | null;
  overhang: string | null;
  table_size: string | null;
  power: string | null;
  contact_person: string | null;
}

export interface DrillingMachinesTranslations {
  id: string;
  languages_code: string | null;
  slug: string | null;
  name: string | null;
  designation: string | null;
  manufacturer: string | null;
  model_type: string | null;
  control_system: string | null;
  milling_spindle: string | null;
  tool_holder: string | null;
  description: unknown | null;
}

export interface Saws {
  id: string;
  status: string | null;
  sort: number | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
  available: boolean | null;
  location: string | null;
  internal_id: string | null;
  year_of_manufacture: number | null;
  condition_key: string | null;
  priority: string | null;
  weight: string | null;
  dimensions: string | null;
  machine_serial_number: string | null;
  roller_diameter: string | null;
  max_cutting_height: string | null;
  cutting_width: string | null;
  table_size: string | null;
  power: string | null;
  contact_person: string | null;
}

export interface SawsTranslations {
  id: string;
  languages_code: string | null;
  slug: string | null;
  name: string | null;
  designation: string | null;
  manufacturer: string | null;
  model_type: string | null;
  control_system: string | null;
  milling_spindle: string | null;
  tool_holder: string | null;
  description: unknown | null;
}

export interface OtherMachines {
  id: string;
  status: string | null;
  sort: number | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
  available: boolean | null;
  location: string | null;
  internal_id: string | null;
  year_of_manufacture: number | null;
  condition_key: string | null;
  priority: string | null;
  weight: string | null;
  dimensions: string | null;
  machine_serial_number: string | null;
  power: string | null;
  contact_person: string | null;
}

export interface OtherMachinesTranslations {
  id: string;
  languages_code: string | null;
  slug: string | null;
  name: string | null;
  designation: string | null;
  manufacturer: string | null;
  model_type: string | null;
  control_system: string | null;
  milling_spindle: string | null;
  tool_holder: string | null;
  description: unknown | null;
  type: string | null;
}

export interface InstockMachines {
  id: string;
  status: string | null;
  sort: number | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
  available: boolean | null;
  location: string | null;
  internal_id: string | null;
  year_of_manufacture: number | null;
  condition_key: string | null;
  priority: string | null;
  weight: string | null;
  dimensions: string | null;
  number_of_axes: number | null;
  travel_x: string | null;
  travel_y: string | null;
  travel_z: string | null;
  travel_a: string | null;
  travel_c: string | null;
  clamping_surface: string | null;
  feed_rate_x: string | null;
  feed_rate_y: string | null;
  feed_rate_z: string | null;
  contact_person: string | null;
}

export interface InstockMachinesTranslations {
  id: string;
  languages_code: string | null;
  slug: string | null;
  name: string | null;
  designation: string | null;
  manufacturer: string | null;
  model_type: string | null;
  control_system: string | null;
  milling_spindle: string | null;
  tool_holder: string | null;
  description: unknown | null;
}

export interface ImageCards {
  id: string;
  seed_key: string | null;
  sort_order: number | null;
  hero_media_block: string | null;
  content_images_block: string | null;
  image: string | null;
  is_image_transparent: boolean | null;
  employee: string | null;
}

export interface ImageCardsTranslations {
  id: string;
  languages_code: string | null;
  title: string | null;
  subtitle: string | null;
}

export interface PreviewCards {
  id: string;
  seed_key: string | null;
  sort_order: number | null;
  explore_more_block: string | null;
  thumbnail: string | null;
  is_image_transparent: boolean | null;
}

export interface PreviewCardsTranslations {
  id: string;
  languages_code: string | null;
  title: string | null;
  subtitle: string | null;
  content: string | null;
  cta_text: string | null;
  redirect_slug: string | null;
}

export interface VariantCards {
  id: string;
  seed_key: string | null;
  sort_order: number | null;
  explore_variants_block: string | null;
  image: string | null;
}

export interface VariantCardsTranslations {
  id: string;
  languages_code: string | null;
  title: string | null;
}

export interface VariantAccordionItems {
  id: string;
  seed_key: string | null;
  sort_order: number | null;
  variant_card: string | null;
}

export interface VariantAccordionItemsTranslations {
  id: string;
  languages_code: string | null;
  title: string | null;
  lines: unknown | null;
}

export interface HistoryEntries {
  id: string;
  seed_key: string | null;
  sort_order: number | null;
  history_block: string | null;
  year: number | null;
}

export interface HistoryEntriesTranslations {
  id: string;
  languages_code: string | null;
  title: string | null;
  description: string | null;
}

export interface DefaultCards {
  id: string;
  seed_key: string | null;
  sort_order: number | null;
  default_cards_block: string | null;
  thumbnail: string | null;
  anchor: string | null;
}

export interface DefaultCardsTranslations {
  id: string;
  languages_code: string | null;
  title: string | null;
  content: string | null;
  buttons: unknown | null;
}

export interface Accordions {
  id: string;
  seed_key: string | null;
  sort_order: number | null;
  content_accordion_block: string | null;
}

export interface AccordionsTranslations {
  id: string;
  languages_code: string | null;
  title: string | null;
  section_title: string | null;
}

export interface AccordionItems {
  id: string;
  seed_key: string | null;
  sort_order: number | null;
  accordion: string | null;
  image: string | null;
  is_image_transparent: boolean | null;
}

export interface AccordionItemsTranslations {
  id: string;
  languages_code: string | null;
  title: string | null;
  subtitle: string | null;
  description: string | null;
}

export interface TableDefs {
  id: string;
  seed_key: string | null;
  sort_order: number | null;
  content_table_block: string | null;
}

export interface TableDefsTranslations {
  id: string;
  languages_code: string | null;
  title: string | null;
}

export interface TableColumns {
  id: string;
  seed_key: string | null;
  sort_order: number | null;
  table_def: string | null;
}

export interface TableColumnsTranslations {
  id: string;
  languages_code: string | null;
  column_label: string | null;
  rows: unknown | null;
}

export interface BlockHeroCarousel {
  id: string;
  seed_key: string | null;
  carousel_speed: number | null;
}

export interface BlockHeroCarouselTranslations {
  id: string;
  languages_code: string | null;
  keyphrase: string | null;
}

export interface BlockHeroDual {
  id: string;
  seed_key: string | null;
  image: string | null;
  secondary_image: string | null;
}

export interface BlockHeroDualTranslations {
  id: string;
  languages_code: string | null;
  keyword: string | null;
  sub_keyword: string | null;
  title: string | null;
  subtitle: string | null;
  content: string | null;
}

export interface BlockHeroMedia {
  id: string;
  seed_key: string | null;
  media: string | null;
  anchor: string | null;
}

export interface BlockHeroMediaTranslations {
  id: string;
  languages_code: string | null;
  title: string | null;
  description: string | null;
}

export interface BlockTextImage {
  id: string;
  seed_key: string | null;
  image: string | null;
}

export interface BlockTextImageTranslations {
  id: string;
  languages_code: string | null;
  title: string | null;
  subtitle: string | null;
  content: string | null;
}

export interface BlockPageHeader {
  id: string;
  seed_key: string | null;
  anchor: string | null;
}

export interface BlockPageHeaderTranslations {
  id: string;
  languages_code: string | null;
  headline: string | null;
  description: string | null;
}

export interface BlockUspList {
  id: string;
  seed_key: string | null;
}

export interface BlockUspListTranslations {
  id: string;
  languages_code: string | null;
  items: unknown | null;
}

export interface BlockExploreMore {
  id: string;
  seed_key: string | null;
}

export interface BlockExploreMoreTranslations {
  id: string;
  languages_code: string | null;
  section_title: string | null;
  description: string | null;
}

export interface BlockExploreVariants {
  id: string;
  seed_key: string | null;
}

export interface BlockExploreVariantsTranslations {
  id: string;
  languages_code: string | null;
  section_title: string | null;
}

export interface BlockHistory {
  id: string;
  seed_key: string | null;
}

export interface BlockHistoryTranslations {
  id: string;
  languages_code: string | null;
  section_title: string | null;
}

export interface BlockDefaultCards {
  id: string;
  seed_key: string | null;
  is_dark_mode: boolean | null;
  anchor: string | null;
}

export interface BlockDefaultCardsTranslations {
  id: string;
  languages_code: string | null;
  section_title: string | null;
  description: string | null;
}

export interface BlockCollectionList {
  id: string;
  seed_key: string | null;
  source: string | null;
  display: string | null;
}

export interface BlockCollectionListTranslations {
  id: string;
  languages_code: string | null;
  section_title: string | null;
  description: string | null;
}

export interface BlockContactForm {
  id: string;
  seed_key: string | null;
  employee: string | null;
}

export interface BlockContentHeader {
  id: string;
  seed_key: string | null;
  is_dark_mode: boolean | null;
  anchor: string | null;
}

export interface BlockContentHeaderTranslations {
  id: string;
  languages_code: string | null;
  section_title: string | null;
  description: string | null;
}

export interface BlockContentTextImage {
  id: string;
  seed_key: string | null;
  is_dark_mode: boolean | null;
  image_position: string | null;
  image_size: string | null;
  is_image_transparent: boolean | null;
  image: string | null;
}

export interface BlockContentTextImageTranslations {
  id: string;
  languages_code: string | null;
  title: string | null;
  content: unknown | null;
}

export interface BlockContentImages {
  id: string;
  seed_key: string | null;
  is_dark_mode: boolean | null;
}

export interface BlockContentAccordion {
  id: string;
  seed_key: string | null;
  is_dark_mode: boolean | null;
}

export interface BlockContentAccordionTranslations {
  id: string;
  languages_code: string | null;
  title: string | null;
}

export interface BlockContentTable {
  id: string;
  seed_key: string | null;
  is_dark_mode: boolean | null;
}

export interface BlockSpacer {
  id: string;
  seed_key: string | null;
  is_dark_mode: boolean | null;
  height: string | null;
  with_separator_line: boolean | null;
}

export interface Global {
  id: string;
  status: string | null;
  seed_key: string | null;
  site_name: string | null;
  site_description: string | null;
  keywords: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  address: string | null;
}

export interface Homepage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface HomepageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface AboutUsPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface AboutUsPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface IndustriesPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface IndustriesPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface Career {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface CareerTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface NewsPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface NewsPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface LegalNoticePage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface LegalNoticePageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface PrivacyPolicyPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface PrivacyPolicyPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface CncMillsPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface CncMillsPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface ConventionalMillsPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface ConventionalMillsPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface LathesPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface LathesPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface MillingMachinesPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface MillingMachinesPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface GrindingMachinesPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface GrindingMachinesPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface DrillingMachinesPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface DrillingMachinesPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface SawsPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface SawsPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface OtherMachinesPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface OtherMachinesPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface GantryMachinesPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface GantryMachinesPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface InstockPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface InstockPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface UsedMachinesPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface UsedMachinesPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface Fs10Page {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface Fs10PageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface Fs15Page {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface Fs15PageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface Fs20Page {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface Fs20PageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface StyrospeedHsPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface StyrospeedHsPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface ShankRaspCutterPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface ShankRaspCutterPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface SpecialMillingCutterPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface SpecialMillingCutterPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface BriquettingPressPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface BriquettingPressPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface MachineMaintenancePage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface MachineMaintenancePageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface MachineMarketingPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface MachineMarketingPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface MachineModernizationPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface MachineModernizationPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface AdhesivePage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface AdhesivePageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface MetalsPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface MetalsPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface PlasticsPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface PlasticsPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface StyrofoamPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface StyrofoamPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface StyrofoamProcessingPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface StyrofoamProcessingPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface RawMaterialPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface RawMaterialPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface HollowMillingSpindlePage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface HollowMillingSpindlePageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface MillingToolsPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface MillingToolsPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface PressesPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface PressesPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface ShredderPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface ShredderPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface SuctionSystemPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface SuctionSystemPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface HybridPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface HybridPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface ModelConstructionMachinesPage {
  id: string;
  status: string | null;
  seed_key: string | null;
  date_created: string | null;
  date_updated: string | null;
}

export interface ModelConstructionMachinesPageTranslations {
  id: string;
  languages_code: string | null;
  seo_page_title: string | null;
  seo_page_description: string | null;
  seo_keywords: string | null;
}

export interface DirectusSchema {
  employees: Employees;
  brochures: Brochures;
  downloads: Downloads;
  fairs: Fairs;
  job_ads: JobAds;
  social_media_channels: SocialMediaChannels;
  testimonials: Testimonials;
  contact_requests: ContactRequests;
  cnc_mills: CncMills;
  conventional_mills: ConventionalMills;
  lathes: Lathes;
  milling_machines: MillingMachines;
  grinding_machines: GrindingMachines;
  drilling_machines: DrillingMachines;
  saws: Saws;
  other_machines: OtherMachines;
  instock_machines: InstockMachines;
  image_cards: ImageCards;
  preview_cards: PreviewCards;
  variant_cards: VariantCards;
  variant_accordion_items: VariantAccordionItems;
  history_entries: HistoryEntries;
  default_cards: DefaultCards;
  accordions: Accordions;
  accordion_items: AccordionItems;
  table_defs: TableDefs;
  table_columns: TableColumns;
  block_hero_carousel: BlockHeroCarousel;
  block_hero_dual: BlockHeroDual;
  block_hero_media: BlockHeroMedia;
  block_text_image: BlockTextImage;
  block_page_header: BlockPageHeader;
  block_usp_list: BlockUspList;
  block_explore_more: BlockExploreMore;
  block_explore_variants: BlockExploreVariants;
  block_history: BlockHistory;
  block_default_cards: BlockDefaultCards;
  block_collection_list: BlockCollectionList;
  block_contact_form: BlockContactForm;
  block_content_header: BlockContentHeader;
  block_content_text_image: BlockContentTextImage;
  block_content_images: BlockContentImages;
  block_content_accordion: BlockContentAccordion;
  block_content_table: BlockContentTable;
  block_spacer: BlockSpacer;
  global: Global;
  homepage: Homepage;
  about_us_page: AboutUsPage;
  industries_page: IndustriesPage;
  career: Career;
  news_page: NewsPage;
  legal_notice_page: LegalNoticePage;
  privacy_policy_page: PrivacyPolicyPage;
  cnc_mills_page: CncMillsPage;
  conventional_mills_page: ConventionalMillsPage;
  lathes_page: LathesPage;
  milling_machines_page: MillingMachinesPage;
  grinding_machines_page: GrindingMachinesPage;
  drilling_machines_page: DrillingMachinesPage;
  saws_page: SawsPage;
  other_machines_page: OtherMachinesPage;
  gantry_machines_page: GantryMachinesPage;
  instock_page: InstockPage;
  used_machines_page: UsedMachinesPage;
  fs10_page: Fs10Page;
  fs15_page: Fs15Page;
  fs20_page: Fs20Page;
  styrospeed_hs_page: StyrospeedHsPage;
  shank_rasp_cutter_page: ShankRaspCutterPage;
  special_milling_cutter_page: SpecialMillingCutterPage;
  briquetting_press_page: BriquettingPressPage;
  machine_maintenance_page: MachineMaintenancePage;
  machine_marketing_page: MachineMarketingPage;
  machine_modernization_page: MachineModernizationPage;
  adhesive_page: AdhesivePage;
  metals_page: MetalsPage;
  plastics_page: PlasticsPage;
  styrofoam_page: StyrofoamPage;
  styrofoam_processing_page: StyrofoamProcessingPage;
  raw_material_page: RawMaterialPage;
  hollow_milling_spindle_page: HollowMillingSpindlePage;
  milling_tools_page: MillingToolsPage;
  presses_page: PressesPage;
  shredder_page: ShredderPage;
  suction_system_page: SuctionSystemPage;
  hybrid_page: HybridPage;
  model_construction_machines_page: ModelConstructionMachinesPage;
}
