import { allCollections } from './index.js';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const OUT = new URL('../../../shared/types/directus.ts', import.meta.url).pathname;

function tsType(t: string): string {
  switch (t) {
    case 'integer':
    case 'bigInteger':
    case 'float':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'json':
      return 'unknown';
    default:
      return 'string';
  }
}

function collectionInterface(name: string, fields: { field: string; type: string }[]): string {
  const lines = fields.map((f) => `  ${f.field}: ${tsType(f.type)} | null;`);
  const pascal = name
    .split('_')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
  return `export interface ${pascal} {\n  id: string;\n${lines.join('\n')}\n}\n`;
}

const parts: string[] = [
  '// AUTO-GENERATED by seed/src/schema/generate-types.ts — do not edit by hand',
  '',
];

for (const c of allCollections) {
  parts.push(collectionInterface(c.name, c.fields));
  if (c.translatable && c.translationFields) {
    parts.push(
      collectionInterface(`${c.name}_translations`, [
        { field: 'languages_code', type: 'string' },
        ...c.translationFields,
      ]),
    );
  }
}

const schemaMap = allCollections
  .map((c) => `  ${c.name}: ${c.name.split('_').map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join('')};`)
  .join('\n');

parts.push(`export interface DirectusSchema {\n${schemaMap}\n}\n`);

const dir = dirname(OUT);
mkdirSync(dir, { recursive: true });
writeFileSync(OUT, parts.join('\n'), 'utf8');
console.log('✔ Wrote', OUT);
